version: '3.0'
services:
  rasa:
    image: rasa_img:latest
    user: root
    build:
      context: .
    volumes:
      - ./:/app
      - ./credentials.yml:/app/credentials.yml
      - ./models:/app/models
      - ./endpoints.yml:/app/endpoints.yml
      - ./config.yml:/app/config.yml
      - ./excel_files:/app/excel_files
    ports:
      - 5005:5005
    depends_on:
      - action_server
    command:
      - run
      - -m
      - models
      - --enable-api
      - --cors
      - "*"

  action_server:
    image: ac_img:latest
    build:
      context: actions
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
      - ./excel_files:/app/excel_files
    ports:
      - 5055:5055

  redis:
    image: redis:latest
     
  webchat:
    image: nginx:latest
    ports:
      - 7739:80  #HTTP
      - 443:443  #HTTPS
    volumes:
      - ./webchat:/usr/share/nginx/html
      - ./excel_files:/usr/share/nginx/html/excel_files
      - ./tstkeys:/etc/nginx/cert/tstkey
